# Generated by Django 4.1.4 on 2023-08-19 11:12

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Indicator',
            fields=[
                ('id_indicator', models.AutoField(primary_key=True, serialize=False)),
                ('indicator_name', models.CharField(max_length=100, validators=[django.core.validators.MinValueValidator(20)])),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('login', models.CharField(max_length=20, validators=[django.core.validators.MinValueValidator(1)])),
                ('password', models.CharField(max_length=20, validators=[django.core.validators.MinValueValidator(1)])),
                ('token', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Record',
            fields=[
                ('id_record', models.AutoField(primary_key=True, serialize=False)),
                ('date_record', models.DateField()),
                ('login', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webapi.user')),
            ],
        ),
        migrations.CreateModel(
            name='ListIndicators',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.FloatField()),
                ('id_indicator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webapi.indicator')),
                ('id_record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webapi.record')),
            ],
        ),
        migrations.CreateModel(
            name='IFC',
            fields=[
                ('id_ifc', models.AutoField(primary_key=True, serialize=False)),
                ('date_ifc', models.DateField()),
                ('path', models.CharField(max_length=100)),
                ('id_record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webapi.record')),
            ],
        ),
    ]
